package com.je.playground.ui.theme

import androidx.compose.ui.graphics.Color

//val darkSecondary = Color(0xFFCCC5B9)
val highlightDark = Color(0xFFEB5E28)

val primaryDark = Color(0xFF1B1B1B)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF1B1B1B)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val inversePrimaryDark = Color(0xFF1B1B1B)
val secondaryDark = Color(0xFF2B2B2B)
val onSecondaryDark = Color(0xFF1B1B1B)
val secondaryContainerDark = Color(0xFF2B2B2B)
val onSecondaryContainerDark = Color(0xFF1B1B1B)
val tertiaryDark = Color(0xFF1B1B1B)
val onTertiaryDark = Color(0xFF1B1B1B)
val tertiaryContainerDark = Color(0xFF1B1B1B)
val onTertiaryContainerDark = Color(0xFF1B1B1B)
val backgroundDark = Color(0xFF3D3B38)
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0xFF1B1B1B)
val onSurfaceDark = Color(0xFF1B1B1B)
val surfaceVariantDark = Color(0xFF1B1B1B)
val onSurfaceVariantDark = Color(0xFF1B1B1B)
val surfaceTintDark = Color(0xFF1B1B1B)
val inverseSurfaceDark = Color(0xFF1B1B1B)
val inverseOnSurfaceDark = Color(0xFF1B1B1B)
val errorDark = Color(0xFF1B1B1B)
val onErrorDark = Color(0xFF1B1B1B)
val errorContainerDark = Color(0xFF1B1B1B)
val onErrorContainerDark = Color(0xFF1B1B1B)
val outlineDark = Color(0xFF1B1B1B)
val outlineVariantDark = Color(0xFF1B1B1B)
val scrimDark = Color(0xFF1B1B1B)


val lightPrimary = Color(0xFFF0EBE4)
val lightPrimaryVariant = Color(0xFFBFAD8F)
val lightSecondary = Color(0xFF000000)
val lightSecondaryVariant = Color(0xFF4D4D4D)
//val lightSecondaryVariant = Color(0xFF808080)

val primaryLight = Color(0xFFF0EBE4)
val onPrimaryLight = Color(0xFF000000)
val primaryContainerLight = Color(0xFF1B1B1B)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val inversePrimaryLight = Color(0xFF1B1B1B)
val secondaryLight = Color(0xFF1B1B1B)
val onSecondaryLight = Color(0xFF1B1B1B)
val secondaryContainerLight = Color(0xFF1B1B1B)
val onSecondaryContainerLight = Color(0xFF1B1B1B)
val tertiaryLight = Color(0xFF1B1B1B)
val onTertiaryLight = Color(0xFF1B1B1B)
val tertiaryContainerLight = Color(0xFF1B1B1B)
val onTertiaryContainerLight = Color(0xFF1B1B1B)
val backgroundLight = Color(0xFFBFAD8F)
val onBackgroundLight = Color(0xFFFFFFFF)
val surfaceLight = Color(0xFF1B1B1B)
val onSurfaceLight = Color(0xFF1B1B1B)
val surfaceVariantLight = Color(0xFF1B1B1B)
val onSurfaceVariantLight = Color(0xFF1B1B1B)
val surfaceTintLight = Color(0xFF1B1B1B)
val inverseSurfaceLight = Color(0xFF1B1B1B)
val inverseOnSurfaceLight = Color(0xFF1B1B1B)
val errorLight = Color(0xFF1B1B1B)
val onErrorLight = Color(0xFF1B1B1B)
val errorContainerLight = Color(0xFF1B1B1B)
val onErrorContainerLight = Color(0xFF1B1B1B)
val outlineLight = Color(0xFF1B1B1B)
val outlineVariantLight = Color(0xFF1B1B1B)
val scrimLight = Color(0xFF1B1B1B)


//val darkSecondaryVariant = Color(0xFF808080)

val darkPrimary = Color(0xFF1B1B1B)
val darkPrimaryVariant = Color(0xFF3D3B38)
val darkSecondary = Color(0xFFFFFFFF)
val darkSecondaryVariant = Color(0xFFCCCCCC)
//val darkSecondaryVariant = Color(0xFF808080)

val onPrimary = Color(0xFF00C853)
val onSecondary = Color(0xFFFF4A0E)

//val darkSecondaryVariant = Color(0xFF99948B)
//val darkSecondary = Color(0xFF323232)
//val darkSecondary = Color(0xFFFFFCF2)


